### ISSUE TITLE
getClientIp() return the server public IP

### ISSUE THREAD

**Issue by ghost** [KnpLabs/KnpRadBundle#78]
Hi,

In my app I want to use the user IP.

I use:

```
$this->container->get('request')->getClientIp()
```

And get server public IP

I'm on 

```
dev-develop@dev
```

**Comment by gquemener** [comment]
Your problem is not part of the Rad Bundle but of the HttpFoundation component.

I suggest you find some resources on symfony's issue tracker (https://github.com/symfony/symfony/issues, https://github.com/symfony/symfony/issues/7553) or post your problem through the mailing-list, IRC, ... (http://symfony.com/community).

Thanks
